name: dfapi_auth
description: DfApi Authetication based on flutter_appauth package and identity server.
version: 0.1.8
repository: https://github.com/iemektar/dfapi_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  flutter_appauth: ^0.9.2+6
  get_it: ^5.0.6
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  meta: ^1.2.4
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: