name: dfapi_auth
description: DfApi Authetication based on flutter_appauth package and identity server.
version: 1.0.0
repository: https://github.com/iemektar/dfapi_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  get_it: ^5.0.6
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  equatable: ^1.2.6
  custom_response: ^0.0.1
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: