name: dfapi_auth
description: DfApi Authetication based on flutter_appauth package and identity server.
version: 1.0.3
repository: https://github.com/iemektar/dfapi_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  get_it: ^5.0.6
  shared_preferences: ^2.0.5
  http: ^0.12.2
  equatable: ^2.0.0
  custom_response: ^0.0.1
  flutter_icons: ^1.1.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: